import Head from 'next/head'
import Image from 'next/image'
//import styles from '../styles/Home.module.css'
import { FaRegEnvelope } from 'react-icons/fa'
import { BsFillCalendarWeekFill } from 'react-icons/bs'
import { BsFillTelephoneFill} from 'react-icons/bs'
import { MdLocationOn} from 'react-icons/md'
import { BsFillPersonLinesFill} from 'react-icons/bs'





 function Formulaire_qualifs() {
  return (
    <div className=" items-center justify-center mt-5 h-full w-full xl:pl-6 xl:pr-6 xl:pb-16 xl:py-6 bg-[#0e1373]">
      <Head>
        <title>Formulaire des qualifications</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col space-y-[15px] items-center justify-center w-full   text-center   ">
        {/* Sign in section */}
        {/* <div className="bg-white rounded-3xl  flex flex-col flex:w-full justify-center  shadow-2xl md:w-full xl:w-full "> */}
        <div className="bg-white rounded-2xl shadow-3xl md:w-full xl:w-full  flex-col flex:w-full  ">

          <div className=" p-5 md:shrink-0">
            
            <div className="py-10 text-[#0e1373]">
              <h2 className="text-3xl font-bold mb-2">Qualifications</h2>
              <div className="flex flex-col items-center w-full">
              <div className="bg-gray-100 flex items-center w-64 p-2 mb-3">
                  <BsFillPersonLinesFill className="text-gray-400 m-2" />
                  <input
                    type="text"
                    name="Type de qualifications"
                    placeholder="Type de qualifications"
                    className="text-sm bg-gray-100 outline-none flex-1  "
                  />
                </div>
               
                <div className="bg-gray-100 flex items-center w-64 p-2 mb-3">
                  <BsFillCalendarWeekFill className="text-gray-400 m-2" />
                  Date d'obtention de la qualif   
                  <input
                    type="date"
                    name="Date d'obtention"
                    placeholder="recrutement ONDA TETOUAN "
                    className="text-sm bg-gray-100 outline-none flex-1"
                  />
                </div>
               
                <a
                  href="#"
                  className="border-2 border-[#0e1373] rounded-full px-12 mt-8 py-2 inline-block font-semibold hover:bg-[#0e1373] hover:text-gray-100"
                >
                  Enregistrer
                </a>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}

export default Formulaire_qualifs;
