import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FaRegEnvelope } from 'react-icons/fa'
import { MdLockOutline } from 'react-icons/md'
import logoImage from '../public/logoImage.jpeg'
const Login = () => {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen xl:py-2 bg-gray-100 ">
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex flex-col items-center justify-center w-full flex-1 xl:px-20 text-center  ">
        {/* Sign in section */}
        <div className="bg-white rounded-2xl shadow-2xl md:flex xl:w-2/3 max-w-4xl">
          <div className="xl:w-1/2 p-5 md:shrink-0">
            <div className=" font-bold text-[#0e1373] text-center sm:text-left">
              <Image src={logoImage} alt="/" width={220} height={110} />
            </div>
            <div className="py-10 text-[#0e1373]">
              <h2 className="text-3xl font-bold mb-2">Sign in to Account</h2>
              <p className="text-gray-400 mb-10 mt-5">Use your email account</p>
              <div className="flex flex-col items-center">
                <div className="bg-gray-100 flex items-center w-64 p-2 mb-3">
                  <FaRegEnvelope className="text-gray-400 m-2" />
                  <input
                    type="email"
                    name="email"
                    placeholder="Email"
                    className="text-sm bg-gray-100 outline-none flex-1"
                  />
                </div>
                <div className="bg-gray-100 flex items-center w-64 p-2 mb-3">
                  <MdLockOutline className="text-gray-400 m-2" />
                  <input
                    type="password"
                    name="password"
                    placeholder="password"
                    className="text-sm bg-gray-100 outline-none flex-1"
                  />
                </div>
                <div className=" flex w-64 mt-5 justify-between">
                  <label htmlFor="#" className="text-xs flex items-center">
                    <input type="checkbox" name="remember" className="mr-1" />
                    Remember me
                  </label>
                  <a href="#" className="text-xs">
                    <p>Forgot Password?</p>
                  </a>
                </div>
                <a
                  href="#"
                  className="border-2 border-[#0e1373] rounded-full px-12 mt-8 py-2 inline-block font-semibold hover:bg-[#0e1373] hover:text-gray-100"
                >
                  Sign in
                </a>
              </div>
            </div>
          </div>
          <div className="xl:w-1/2 bg-[#0e1373] text-gray-100 rounded-tr-2xl rounded-br-2xl py-36 px-12"></div>
        </div>
      </main>
    </div>
  )
}
export default Login
